### PR TITLE
Xpand.Utils and Xpand.Xpo to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by gerritmulder**
Making these projects .NET Standard 2.0 and future-proof. We are planning to release these both as NuGet packages.

Has been partly discussed in issue https://github.com/eXpandFramework/eXpand/issues/440

### CODE REVIEW

**Comment by gerritmulder** [comment]
Because the XAF modules are using the Fasterflect package for .NET Framework, several projects will have ambiguous types between Fasterflect and Fasterflect.Netstandard. I am trying to find a solution for this.

**Review by apobekiaris — CHANGES_REQUESTED** [review]
why ControlsExtensions has to go? as we discussed net461 base can consume netStd

**Comment by gerritmulder** [comment]
The [Control](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.control?view=netframework-4.8) type is from System.Web which isn't supported for .NET Standard.

**Review by apobekiaris — APPROVED** [review]

**Comment by gerritmulder** [comment]
As for commit https://github.com/eXpandFramework/eXpand.lab/pull/2/commits/163cbf5d68709e15c61e794675c34ba5c01bb0c2 the both NCarousels should be fixed

**Comment by apobekiaris** [comment]
1. I do not see how the fasterflectflect problem is fixed, u just used the unsigned version which will not work
2. Please remove the ChangeAliasOfFasterflectNetFramework targets, when the fasterflect references will be replaced from a working fasterflect version the replacement script should be removed as it is not needed to run anymore and just adds to the support cost. As I told u there are script that run on eacu build https://github.com/eXpandFramework/eXpand/blob/master/Support/Build/UpdateNuspecs.ps1. This script goes through all packagereferences/referneces and automatically generate the nugets.

**Comment by gerritmulder** [comment]
Both questions point to the same problem, I already stated this earlier. If the Utils or Xpo project contains a class that uses a type from the Fasterflect.Netstandard package and that class will be used in for example Xpand.ExpressApp, then Xpand.ExpressApp has to add Fasterflect.Netstandard too. But when Xpand.ExpressApp uses the normal fasterflect package too, then there will be ambigious types. The same problem with the XAF.modules: because they have the normal fasterflect package too, it will cause an ambigious types error.

The ChangeAliasOfFasterflectNetFramework target can be removed when the XAF.modules use Fasterflect.Netstandard too, it is a fix for the ambigious types error.

I understand the unsigned package problem and as we discussed, we may sign our own package. I know this requires much changes, but it has to happen anyways, since .NET Framework will slowly fade away within 5-10 years.

**Comment by apobekiaris** [comment]
can u sign the FasterFlect.Standard locally using the Xpand.Key? and put it in _third_party_assemblies and reference it from there. I cannot merge like this and we cannot have a build.

**Comment by apobekiaris** [comment]
no need to publish it anywhere or cahneg the nugets just replace the references and remove the target afterwards.

**Comment by apobekiaris** [comment]
wondering how come u do not have conflicts with the standalone packages cause they use the full fasterflect also. Anyways once u sign it I ll send a build for them first with the signed assembly

**Comment by gerritmulder** [comment]
> 
> 
> wondering how come u do not have conflicts with the standalone packages cause they use the full fasterflect also. Anyways once u sign it I ll send a build for them first with the signed assembly

Because of the target. The target hides the full fasterflect in the Xpand code. It is only accessible when you use `using extern alias fasterflectNet`

**Comment by apobekiaris** [comment]
spare my time with more details on how this works please, i fail to follow u.

**Comment by gerritmulder** [comment]
So in this picture I have installed Fasterflect.Netstandard and Xpand.XAF.Modules.Reactive, which references fasterflect. As you see it will gives a problem, because both packages contain the same function and namespace.
https://prnt.sc/oc4pq7

In the next picture I added a target in the .csproj file (Directory.build.props does the same, but for all projects). The target creates an extern alias for the official fasterflect package. When using Fasterflect functions it will select Fasterflect.Netstandard, because I hided the official fasterflect package.
https://prnt.sc/oc4rhq

[ExternAliasExample.zip](https://github.com/eXpandFramework/eXpand.lab/files/3368594/ExternAliasExample.zip)

**Comment by apobekiaris** [comment]
i see thnks for the heads up on this feature! However I think it beats the fasterflect flexibility and cannot be used as real solution but only as a workaround when u not have many usages, please correct me if I am wrong. So I think my suggestion of a local signed copy can let us move forward fast.

**Comment by gerritmulder** [comment]
We will not use the alias, it is only to fix the problem with ambigious types. Because of the alias, the fasterflect functions that are used are from the Fasterflect.Netstandard package. If the XAF modules are updated to the fasterflect netstd package, then it can be removed. Because the XAF.Modules use the normal fasterflect package.
I will try to sign the package, because we can't have warnings.

**Review by apobekiaris — APPROVED** [review]

**Comment by gerritmulder** [comment]
The PR is done now, changes can be merged.

**Pull request merged**
