### PR TITLE
Missing using Xpand.XAF.Modules.Reactive.Services;

### PR DESCRIPTION
**Pull request by capricciobob**
using Xpand.XAF.Modules.Reactive.Services; was missing from two files causing a failure to build in Xpand.ExpressApp.ExcelImporter.Win

### CODE REVIEW

**Comment by apobekiaris** [comment]
I do not understand how can a build fails? since it is already published.

**Comment by capricciobob** [comment]
When I open the AllModules in Visual Studio and attempt to build, there are build errors. When the using statements are added, the build errors go away.

**Comment by apobekiaris** [comment]
did u attempt to build.ps1 first?

**Comment by capricciobob** [comment]
Yes, the failure happened with build.ps1 first, then I opened in Visual Studio to find the problem.

**Comment by apobekiaris** [comment]
what I meant before is that Azure builds use the Build.ps1 and the AllModules.sln and they do not fail. Anyway thanks for the PR I will check it

**Comment by capricciobob** [comment]
Look at the log at this page. It is failing.

https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=4801

**Comment by capricciobob** [comment]
Line 654 through 660 of the build log failure is what my change fixes.

**Comment by capricciobob** [comment]
There is another failure on line 670 which I am attempting to find a fix for as well, but it is unrelated to this.

**Comment by apobekiaris** [comment]
yes i see now thnks

**Comment by apobekiaris** [comment]
the build u are working though it fails, so it means that is under works. New packages are introduces so the usings are complain. The plan is to integrate paket b4 release https://fsprojects.github.io/Paket/

**Comment by capricciobob** [comment]
Sounds great. So for now the lab will not build, is that correct? I was trying to verify the Dashboard defect that still doesn't work. Instead of asking you, I was trying to be helpful and fix it myself. ;)

**Comment by apobekiaris** [comment]
thanks for the help feel free to fix anything it makes sense, I can let the build pass if u need it once u verify that it does work on your side.

**Comment by capricciobob** [comment]
There was a missing dependency in the Xpand.ExpressApp.ExcelImporter.Web and XVideoRental.Module.Win csproj file for Extensions. Once I added this back, I get a clean build.ps1

There is still an issue with the Executing VSIX part of build.ps1 though.....

Executing VSIX
MSBuild auto-detection: using msbuild version '16.2.37902.0' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
InvokeScript : 
SerializedRemoteException      : 
SerializedRemoteInvocationInfo : 
ErrorRecord                    : D:\NewGithub\eXpand.lab\Xpand.Plugins\Xpand.VSIX\Xpand.VSIX.csproj(278,11): error MSB4226: The imported project "C:\Program Files 
                                 (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v16.0\VSSDK\Microsoft.VsSDK.targets" was not found. Also, 
                                 tried to find "VSSDK\Microsoft.VsSDK.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files 
                                 (x86)\MSBuild\Microsoft\VisualStudio\v16.0" . These search paths are defined in "C:\Program Files (x86)\Microsoft Visual 
                                 Studio\2019\BuildTools\MSBuild\Current\bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that 
                                 the file exists on disk in one of the search paths.
WasThrownFromThrowStatement    : True

**Comment by capricciobob** [comment]
I was missing some components in Visual Studio for the VSIX items. I can now confirm that this PR gives a clean build.ps1

**Pull request merged**
